version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/London
  open-pull-requests-limit: 30
  groups:
    storybook:
      applies-to: version-updates
      patterns:
      - "@storybook/*"
    typescript-eslint:
      applies-to: version-updates
      patterns:
      - "@typescript-eslint/*"
    babel:
      applies-to: version-updates
      patterns:
      - "@babel/*"
