#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"
dir=$(mktemp -d -t fly-build-boclips-ui.XXXXX)

tidy () {
    rm -rf "$dir"
}

trap tidy EXIT


fly --target ci execute \
    --input source="$cwd" \
    --config "$cwd/pipeline/test.yaml" \
