---
groups:
- name: all
  jobs:
  - test
  - release-candidate-test
  - release

jobs:
- name: test
  plan:
  - get: boclips-ui
    trigger: true
  - task: test
    input_mapping:
      source: boclips-ui
    file: boclips-ui/pipeline/test.yaml

- name: release-candidate-test
  plan:
  - get: boclips-ui
  - get: release-candidate-source
    trigger: true
  - task: test
    input_mapping:
      source: release-candidate-source
    file: boclips-ui/pipeline/test.yaml

- name: release
  plan:
  - get: boclips-ui
  - get: release-candidate-source
    passed: [release-candidate-test]
    trigger: true
  - task: release
    input_mapping:
      source: release-candidate-source
      task-source: boclips-ui
    file: boclips-ui/pipeline/release.yaml
    params:
      NPM_TOKEN: ((npm.token))

resources:
- name: boclips-ui
  type: git
  icon: github
  source:
    branch: master
    private_key: ((boclips-ui.repo-key))
    uri: git@github.com:boclips/boclips-ui.git

- name: release-candidate-source
  type: git
  icon: github
  source:
    branch: master
    private_key: ((boclips-ui.repo-key))
    uri: git@github.com:boclips/boclips-ui.git
    tag_regex: '@boclips-ui\/.*@.*'
    fetch_tags: true
